In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [20]:
a = np.arange(10).reshape(5,2)
a 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
a=a.T
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [22]:
a=a.transpose((1,0))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
print(a.shape)

(2, 3)


In [7]:
print(a.ndim)

2


In [26]:
np.sqrt(a)

array([[0.        , 1.        ],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798],
       [2.44948974, 2.64575131],
       [2.82842712, 3.        ]])